# Generated by Django 5.1.1 on 2024-11-06 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OffreEmploi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
                ("date_expiration", models.DateTimeField()),
                ("entreprise", models.CharField(max_length=255)),
                ("salaire", models.DecimalField(decimal_places=2, max_digits=10)),
                ("localisation", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_candidature", models.DateTimeField(auto_now_add=True)),
                ("cv", models.FileField(blank=True, null=True, upload_to="cv/")),
                ("name", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=20)),
                (
                    "candidat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutement.offreemploi",
                    ),
                ),
            ],
        ),
    ]
