# Generated by Django 5.1.1 on 2024-10-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
