# Generated by Django 5.1.1 on 2024-10-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employe_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='profile_picture',
        ),
    ]
