# Generated by Django 5.1.1 on 2024-11-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_leave"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Leave",
        ),
    ]
