# Generated by Django 5.1.1 on 2024-11-10 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_delete_leave"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_of_leave",
                    models.CharField(
                        choices=[
                            ("maladie", "Congés maladie"),
                            ("vacances", "Congés vacances"),
                            ("maternité", "Congés maternité"),
                            ("sabbatique", "Congés sabbatique"),
                        ],
                        default="maladie",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField(blank=True, default="", null=True)),
                ("approval_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuvee", "Approuvée"),
                            ("rejettee", "Rejetée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True, default="", null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to="users.rh",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="users.employe",
                    ),
                ),
            ],
        ),
    ]
